---

- name: Install Libre office
  apt:
    name: libreoffice
    state: present

- name: Install CAD packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - freecad
      - librecad
